// <auto-generated />
namespace MailPusher.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewPubliserhFields_Code_AmountEmployees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewPubliserhFields_Code_AmountEmployees));
        
        string IMigrationMetadata.Id
        {
            get { return "201704181027542_NewPubliserhFields_Code_AmountEmployees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
