// <auto-generated />
namespace MailPusher.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Publisher_StatusChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Publisher_StatusChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201704041320007_Publisher_StatusChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
